In [1]:
import numpy as np

In [5]:
a=np.arange(15).reshape(3, 5)

In [10]:
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
type(a)

numpy.ndarray

In [20]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a=np.array( [20,30,40,50] )

In [25]:
b=np.arange( 4 )

In [29]:
b**2

array([0, 1, 4, 9])

In [32]:
np.sin(a)*10<30

array([ True,  True,  True,  True])

In [33]:
A = np.array( [[1,1],
               [0,1]] )
B = np.array( [[2,0],
               [3,4]] )                


array([[5, 4],
       [3, 4]])

In [34]:
A*B  # 每个元素按位置乘

array([[2, 0],
       [0, 4]])

In [35]:
A@B # 点乘

array([[5, 4],
       [3, 4]])

In [36]:
A.dot(B) #点乘

array([[5, 4],
       [3, 4]])

In [37]:
a = np.ones((2,3), dtype=int)

In [38]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
b=np.random.random((2,3))

In [41]:
a*=3

In [42]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [43]:
b+=a

In [44]:
b

array([[3.74205182, 3.9245911 , 3.46207604],
       [3.88086721, 3.89471589, 3.73389031]])

In [45]:
np.ones(3)

array([1., 1., 1.])

In [46]:
b = np.arange(12).reshape(3,4)

In [47]:
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
 b.sum(axis=1)         #

array([ 6, 22, 38])

In [52]:
np.ones(3).T.shape

(3,)

In [54]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])